### ISSUE TITLE
Powershell script says winget is unavailable, even if installed

### ISSUE THREAD

**Issue by Merculous** [ETS2LA/Euro-Truck-Simulator-2-Lane-Assist#240]
Windows 10
winget version v1.7.10582

{
    "type": "Debug",
    "logs": "No log file found",
    "settings": "No settings file found.",
    "additional": "OS: Windows \nOS Version: 10.0.19045 \n\nApp version: App version not found. \nPython Version: 3.11.7 \nGit Version: git version 2.43.0.windows.1\n \nDlls installed: \nInput_semantical: False \nScs-telemetry: False \n\nCPU: Name                                            \n\n11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz  \n\n\n\nGPU: Caption                     \n\nNVIDIA GeForce RTX 3060 Ti  \n\n\n\n"
}

Installer never works. The first winget command will always mention (though exists very fast so I had to record just to get the error) this.

```
You do not have winget available on your system, This is most likely because your on a windows version older then 2004. Please update your windows install and try again.
```

Also, the winget from Microsoft Store gives the same error.

**Comment by Tumppi066** [comment]
This is a known issue, we're working on a new installer that doesn't use Winget.

For now you can use the manual instructions here https://wiki.tumppi066.fi/tutorials/installation/ 

I assume we will get it out in a week or so (assuming I have time from my exams) 👍

**Comment by Merculous** [comment]
I have some ideas to install stuff (though I'm not really a windows person). Besides, I've know Python so I could see if there's anything I can help with. Need to keep myself busy. This is a cool project. Will let you know if anything comes up.

**Comment by Tumppi066** [comment]
Yeah join the discord and we can talk about it. I'm always open to more developers in the project!

As far as the installer goes the main issue is actually Microsoft defender. I cannot run any external files or the installer is considered as a "virus"...

I went around it with Winget but clearly that didn't work too well...

**Comment by DylDevs** [comment]
Issue was fixed in the Discord
