### ISSUE TITLE
[Bug]: Regarding the Issue of Spiral Overlapping Routes

### ISSUE THREAD

**Issue by see963852** [ETS2LA/Euro-Truck-Simulator-2-Lane-Assist#250]
### Description

In the navigation map, there are spiral overlapping routes, and the directions can lead to errors. How should this be resolved? For instance, in the image below, when driving to the intersection, vehicles will turn left or right instead of continuing straight ahead.
![image](https://github.com/ETS2LA/Euro-Truck-Simulator-2-Lane-Assist/assets/95551416/148e7ee4-f48e-45f9-aaad-5863dd8a7bd5)

### App Version

0

### Python Version

3.12

### Confirmation

- [X] I accept

**Comment by Tumppi066** [comment]
This is unfortunately an issue with the current implementation of reading the minimap.
Once 2.0 rolls around and we start using the game data for navigation this will be fixed... for now we just have to deal with it.

Also thank you a ton for that illustration, makes it very easy to understand what you're talking about 👍

**Comment by DylDevs** [comment]
Although it shouldn't do that since Glas fixed that in v3, it sill happens sometimes

**Comment by DylDevs** [comment]
Closing this because no messages have been sent, feel free to open the issue again if you have any more questions or thoughts.
