### ISSUE TITLE
[Support]: Using UFLD lane tracking issue

### ISSUE THREAD

**Issue by jwjw2069** [ETS2LA/Euro-Truck-Simulator-2-Lane-Assist#252]
### Description

![image](https://github.com/ETS2LA/Euro-Truck-Simulator-2-Lane-Assist/assets/67804044/3c893cf1-3fb9-4a6c-977f-d6b16fb478be)

### App Version

1.11.39

### Confirmation

- [x] I understand that I am making a public GitHub Issue

**Comment by Tumppi066** [comment]
UFLD is very much deprecated, if you still want to try to use it you will have to join the discord to get the download link 👍

**Comment by DylDevs** [comment]
> UFLD is very much deprecated, if you still want to try to use it you will have to join the discord to get the download link 👍

Hint hint, we have a UFLD installer

**Comment by Tumppi066** [comment]
Oh yeah forgot about that...

**Comment by jwjw2069** [comment]
ah. cheers guys

**Comment by Tumppi066** [comment]
👍 

No worries, always happy to help :D

**Comment by jwjw2069** [comment]
> UFLD is very much deprecated, if you still want to try to use it you will have to join the discord to get the download link 👍
> 
> Edit: For good measure I will add it here https://discord.com/channels/1120719484982939790/1133314159510040608/1134809449391984712
> 
> Instead of UFLD you should use nav detection.

just tried the link and it says the channel is hidden. I will give the nav detection a try im just exploring

**Comment by Tumppi066** [comment]
Oh yeah it's actually deprecated, didn't see that. It's been a while since I've dealt with UFLD :D

Yeah either use the UFLD installer panel or use the much superior nav detect 👍

**Comment by jwjw2069** [comment]
im gonna sack off the UFLD and just use nav ill take your advice lol
does it require me to be doing a job?
