### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'splash' referenced before assignment

### ISSUE THREAD

**Issue by gongfuture** [ETS2LA/Euro-Truck-Simulator-2-Lane-Assist#261]
### Description

after change ONNXRuntime to GPU

Traceback (most recent call last):
  File "e:\LaneAssist\app\main.py", line 625, in <module>
    LoadApplication()
  File "e:\LaneAssist\app\main.py", line 570, in LoadApplication
    CheckForONNXRuntimeChange()
  File "e:\LaneAssist\app\main.py", line 506, in CheckForONNXRuntimeChange
    if not splash or splash == None:
UnboundLocalError: local variable 'splash' referenced before assignment

### App Version

1.11.74

### Confirmation

- [X] I understand that I am making a public GitHub Issue

**Comment by gongfuture** [comment]
https://github.com/ETS2LA/Euro-Truck-Simulator-2-Lane-Assist/blob/b027e392e5ab3b398491e5dab909bff78d8e6b10/main.py#L503-L520

this def needs add `global splash`

**Comment by Tumppi066** [comment]
Thanks for the report, will fix in a few hours.

UFLD is out of the support window though, so we won't fix any massive issues with it as Nav is better and we're focusing on 2.0 now 👍

**Comment by DylDevs** [comment]
> https://github.com/ETS2LA/Euro-Truck-Simulator-2-Lane-Assist/blob/b027e392e5ab3b398491e5dab909bff78d8e6b10/main.py#L503-L520
> 
> this def needs add `global splash`

If this is the issue, I just fixed it. You can run update.bat and then try again.

**Comment by gongfuture** [comment]
It works .Thank you guys.
