### ISSUE TITLE
file not found to  run the app

### ISSUE THREAD

**Issue by mcmillen993** [ETS2LA/Euro-Truck-Simulator-2-Lane-Assist#308]
![Screenshot (58)](https://github.com/user-attachments/assets/c14764d6-54eb-4024-8d0b-1241f169589e)

**Comment by mcmillen993** [comment]
what can i do to fix this

**Comment by Tumppi066** [comment]
It's getting late here so I can't really help that much today.

For now I would first try and reinstall, if that doesn't work then follow the manual installation instructions here:
https://wiki.ets2la.com/tutorials/installation/#manual-installation

**Comment by mcmillen993** [comment]
problem solved ......its doesn't connect with ETS2

**Comment by Tumppi066** [comment]
The tutorial shows how to do it pretty well, just do the first time setup and restart the game 👍
